### ISSUE TITLE
Issue translation "Duplicate %s"

### ISSUE THREAD

**Issue by pixolin** [createwithrani/quickpost#12]
[I have translated](https://translate.wordpress.org/projects/wp-plugins/quickpost/stable/de/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=13327397&filters%5Btranslation_id%5D=92515586) the text string `Duplicate %s` ([file `scr/duplicate-menu-item.js` line 67](https://github.com/createwithrani/quickpost/blob/main/src/duplicate-menu-item.js#L67)) into German, but the button shows "Duplicate Seiten" or "Duplicate Beitrag", i.e. the post type is shown in German while the word "Duplicate" isn't translated at all.

To avoid differences in formal and informal German I also switched both words, translating them into "{posttype} duplizieren" (`%s duplizieren`) which doesn't seem to get reflected.

**Comment by aurooba** [comment]
I found the problem! Thanks for flagging this @pixolin :) This will be fixed in the next plugin update. (The commit that fixed this issue was e22ec439f6f725c1eefb2f4599977b75a9654faf, if you get curious)
