### ISSUE TITLE
Compound text string ist difficult to translate

### ISSUE THREAD

**Issue by pixolin** [createwithrani/quickpost#13]
File `src/add-button.js` uses in line 40 a compound text string which is difficult to translate.

To avoid a difference in formal and informal German, the best translation would be "{post_type} hinzufügen".

Currently the button uses a compound of "Add new" (Erstellen) and Posttype. "Erstellen Seite" and "Seite Erstellen" are both gramatically wrong; the first sounds odd, the second has an incorrect capital "E".

Providing a text string where just the post type is replaced would make it easier to translate: `%s hinzufügen` (as translation for `Add new %s`) would fit to the typical wording in WordPress.

**Comment by aurooba** [comment]
Interesting! So what I'm hearing is that when the term 'add new' is paired with a noun, it often takes a different from than when it is used alone. I didn't know that! That's really good to know.

**Comment by pixolin** [comment]
It seems we are using a word out of context here to create a compound. No idea where the translation "Erstellen" (literally "Create") comes from actually as it isn't part of the translation.
I'm afraid, my skills are too limited here to be of much help. However replacing a compound with text out of context with a new string seems to be a pragmatic approach.

**Comment by aurooba** [comment]
That's okay! I just want to fully understand. the "Erstellen" is part of core WordPress translation. When I switch my WordPress installation to German, I see that term for 'Add New' in the Dashboard. That's where the plugin is also picking it up from.
<img width="501" alt="Screen Shot 2022-02-22 at 11 34 06 AM" src="https://user-images.githubusercontent.com/6925260/155196578-4b1ad830-0134-430b-bc12-89d7df413fed.png">

So then, my follow up question is: is this wrong in WordPress Core?

**Comment by aurooba** [comment]
I want to note that I think your PR is great, and I can use that to then address/fix why the 'Duplicate' is not getting translated too. But before we make any changes, I just want to fully understand what's going on so that I can do better in the future. :)
