### ISSUE TITLE
common.min.css enqueued on front end in 0.1.2

### ISSUE THREAD

**Issue by mrwweb** [createwithrani/quickpost#21]
After upgrading from v0.1.1 to v0.1.2 of the plugin, I found that there were some styles introduced to the front end that were interfering with my theme. Digging in further, I tracked these to the core `common.min.css` sheet. 

`<link rel='stylesheet' id='common-css'  href=.../wp-admin/css/common.min.css?ver=5.9.3' media='all' />`

I've since replicated this finding on a site with Twenty Twenty Two and no plugins except quickpost 0.1.2.

I haven't experimented with this, but I suspect the issue is the [function that's newly run on `init`](https://github.com/createwithrani/quickpost/blob/main/quickpost.php#L47).

**Comment by Graphnic** [comment]
Just to +1 this. I've experienced this on two sites.  One running Genesis and the other Generate Press. Same style sheet being loaded on the front end, regardless of login state as per @mrwweb. /wp-admin/css/common.min.css?ver=5.9.3

**Comment by aurooba** [comment]
Ooh interesting! Thanks for reporting this @mrwweb and @Graphnic! The `init` part was an experiment to avoid a conflict with the Gutenberg plugin. I'll explore an alternative and get this updated quickly. :)

**Comment by mrwweb** [comment]
@aurooba I also wonder if you can work around it by checking for `is_admin()` or even the block editor context. Here's something I use in one of my plugins:

```php
$current_screen = get_current_screen();

if ( isset( $current_screen->is_block_editor ) && (bool) $current_screen->is_block_editor ) {

        // blah blah blah

}
```

**Comment by aurooba** [comment]
Bug has been fixed and the update has been pushed to the repo!

**Comment by mrwweb** [comment]
@aurooba I can see the fix on Github, but I think something must have gone wrong with the deployment in the repository, because [the init hook is still there](https://plugins.trac.wordpress.org/browser/quickpost/tags/0.1.3/quickpost.php#L47).
